- DSCResources/MSFT_xComputer/MSFT_xComputer.psm1
- Tests/xComputermanagement.Tests.ps1
Added name parameter validation and associated test cases.
> Enhancement #15: Name parameter validation

- DSCResources/MSFT_xOfflineDomainJoin/MSFT_xOfflineDomainJoin.psm1
- DSCResources/MSFT_xOfflineDomainJoin/en-us/MSFT_xOfflineDomainJoin.psd1
- README.md
Correct spelling mistake in DomainAlreadyJoinedhMessage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/28)
> Correct to DomainAlreadyJoinedhMessage variable name

- DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1
- DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.schema.mof
- Examples/Sample_xScheduledTask.ps1
- README.md
- Tests/Integration/MSFT_xScheduledTask.Config.ps1
- Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1
- Tests/Unit/MSFT_xScheduledTask.Tests.ps1
- appveyor.yml
This PR includes a new resource for managing scheduled tasks. It's not something that is flexible enough for every possible scenario to do with managed tasks, but will allow the scheduling of tasks that recur every X number of minutes/hours/days, and you can control the account they execute with. 
Unit tests, examples and readme have all been updated, and all existing tests still pass.
Let me know if you need anything else with this one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/30)
> Added xScheduledTask resource

- README.md
- xComputerManagement.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/39)
> Fixes for Release 1.7.0.0

- DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/36)
> Fixed bug with different OS versions returning repeat interval differently

- DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1
- README.md
- appveyor.yml
- xComputerManagement.psd1
Releasing version 1.8.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/42)
> Release of version 1.8.0.0 of xComputerManagement

- DSCResources/MSFT_xComputer/MSFT_xComputer.psm1
- DSCResources/MSFT_xComputer/MSFT_xComputer.schema.mof
- Examples/xComputer/6-SetComputerDescriptionInWorkgroup.ps1
- README.md
- Tests/Unit/MSFT_xComputer.Tests.ps1
This PR adds the ability to set the computer description through the xComputerManagement module. Along with that, the unit tests have been updated for the computer description and the examples have been updated.
Fixes #67
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/99)
> xComputer: Added Description

- DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1
- DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.schema.mof
- Examples/xScheduledTask/1-CreateScheduledTaskOnce.ps1
- Examples/xScheduledTask/10-RunPowerShellTaskOnceAsUserInteractiveOnly.ps1
- Examples/xScheduledTask/2-CreateScheduledTaskDaily.ps1
- Examples/xScheduledTask/3-CreateScheduledTasksDailyIndefinitely.ps1
- Examples/xScheduledTask/4-CreateScheduledTasksWeekly.ps1
- Examples/xScheduledTask/5-CreateScheduledTasksAtLogon.ps1
- Examples/xScheduledTask/6-CreateScheduledTasksAtStartup.ps1
- Examples/xScheduledTask/9-RunPowerShellTaskOnceAsUserWithHighestPriveleges.ps1
- README.md
- Tests/Integration/MSFT_xScheduledTask.Config.ps1
- Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1
- Tests/Unit/MSFT_xPowerPlan.Tests.ps1
- Tests/Unit/MSFT_xScheduledTask.Tests.ps1
Add support for RunLevel and LogonType to xScheduledTask
- #107 
**Task list:**
@johlju  - would you mind reviewing if you get a moment? Thank you sir!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/112)
> xScheduledTask: Add support for RunLevel and LogonType - Fixes #107

- DSCResources/MSFT_xPowerPlan/MSFT_xPowerPlan.psm1
- DSCResources/MSFT_xPowerPlan/MSFT_xPowerPlan.schema.mof
- DSCResources/MSFT_xPowerPlan/en-US/MSFT_xPowerPlan.schema.mfl
- DSCResources/MSFT_xPowerPlan/en-US/MSFT_xPowerPlan.strings.psd1
- README.md
- Tests/Unit/MSFT_xPowerPlan.Tests.ps1
Convert the xPowerPlan resource to meet HQRM guidelines. Also convert exceptions to throw using standard functions.
- Fixes #116
**Task list:**
@Johlju - if you wouldn't mind (no rush) reviewing this for me? That would be awesome and very much appreciated!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/117)
> Updated xPowerPlan to HQRM - Fixes #116

- CHANGELOG.md
- README.md
Fix master branch AppVeyor badge link URL in README.MD 
- #140 
**Task list:**
@johlju - would you mind reviewing this one - should be pretty trivial :grin:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/141)
>  Fix master branch AppVeyor badge link URL in README.MD - Fixes #140

- CHANGELOG.md
- README.md
This PR adds information about the xScheduledTask dependencies to README.MD.
- Fixes #108
**Task list:**
@johlju - I know you're busy with work ATM, but when you're back could you review this one for me? It is just a minor documentation change so should be trivial! Thanks sir.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/146)
> Added dependency information for xScheduledTask to README.MD - Fixes #108

- CHANGELOG.md
- Modules/ComputerManagementDsc/DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
- Modules/ComputerManagementDsc/DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.schema.mof
- Modules/ComputerManagementDsc/DSCResources/MSFT_ScheduledTask/en-US/MSFT_ScheduledTask.strings.psd1
- Modules/ComputerManagementDsc/Examples/Resources/ScheduledTask/15-CreateScheduledTaskOnceSynchronizeAcrossTimeZoneEnabled.ps1
- Tests/Integration/MSFT_ScheduledTask.Config.ps1
- Tests/Integration/MSFT_ScheduledTask.Integration.Tests.ps1
- Tests/Unit/MSFT_ScheduledTask.Tests.ps1
The ScheduledTask resource currently has no support to set the "synchronize across time zone" checkbox which is available in the Scheduled Task GUI. To make matters worse, the behaviour is also different between operating systems. When the scheduled task resource executes on W2012R2 this option is disabled by default, but when executed on W2016 the option in suddenly enabled.
As the issue that is open for this problem mentions, this also impacts the time the scheduled task is executed when there are daylight savings time changes, like the upcoming one the end of October. Would be great if we can merge this one for the next DSC Resource Kit Wave release (24th of October). 
- Fixes #109  …
> ScheduledTask: Synchronize across time zone support

- .vscode/analyzersettings.psd1
- .vscode/settings.json
- CHANGELOG.md
This PR adds .VSCode settings for applying DSC PSSA rules.
- Fixes #189 
@johlju - would you mind reviewing?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/190)
> Added .VSCode settings for applying DSC PSSA rules - Fixes #189

- CHANGELOG.md
- Modules/ComputerManagementDsc/ComputerManagementDsc.psd1
Releasing version 6.1.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/201)
> Release of version 6.1.0.0 of ComputerManagementDsc

- CHANGELOG.md
- Modules/ComputerManagementDsc/ComputerManagementDsc.psd1
- Modules/ComputerManagementDsc/DSCResources/MSFT_WindowsEventLog/MSFT_WindowsEventLog.psm1
- Modules/ComputerManagementDsc/DSCResources/MSFT_WindowsEventLog/MSFT_WindowsEventLog.schema.mof
- Modules/ComputerManagementDsc/DSCResources/MSFT_WindowsEventLog/README.md
- Modules/ComputerManagementDsc/DSCResources/MSFT_WindowsEventLog/en-US/MSFT_WindowsEventLog.strings.psd1
- Modules/ComputerManagementDsc/Examples/Resources/WindowsEventlog/1-SetWindowsEventlogSize.ps1
- Modules/ComputerManagementDsc/Examples/Resources/WindowsEventlog/2-SetWindowsEventlogLogMode.ps1
- Modules/ComputerManagementDsc/Examples/Resources/WindowsEventlog/3-EnableWindowsEventLog.ps1
- Modules/ComputerManagementDsc/Examples/Resources/WindowsEventlog/4-SetWindowsEventlogLogMode.ps1
- Modules/ComputerManagementDsc/Examples/Resources/WindowsEventlog/5-SetWindowsEventlogSecurityDescriptor.ps1
- Modules/ComputerManagementDsc/Examples/Resources/WindowsEventlog/6-DisableWindowsEventlog.ps1
- README.md
- Tests/Integration/MSFT_WindowsEventLog.Integration.Tests.ps1
- Tests/Integration/MSFT_WindowsEventLog.config.ps1
- Tests/Unit/MSFT_WindowsEventLog.Tests.ps1
Releasing version 6.2.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/208)
> Release of version 6.2.0.0 of ComputerManagementDsc

- README.md
This PR adds a link to the CHANGELOG to the README file, to keep consistent with the other DSC Resource modules.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/223)
> ComputerMangementDsc: Add Change log link to README

- CHANGELOG.md
- DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
- Tests/Unit/MSFT_ScheduledTask.Tests.ps1
This PR ensures that the Delay property is properly set on AtLogon and AtStartup tasks as well when the resource is executed on W2016+ / W10+ (the lower level OS do not support the Delay property as they are not a part of the object returned by New-ScheduledTaskTrigger)
- Fixes #230 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/238)
> ScheduledTask: Fix delay property bug

- CHANGELOG.md
- DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
- DSCResources/MSFT_WindowsEventLog/MSFT_WindowsEventLog.psm1
Fix minor style issues in statement case as per: https://github.com/PowerShell/DscResource.Tests/pull/346
@johlju, would you mind reviewing this for me?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/259)
> Fix minor style issues in statement case

- CHANGELOG.md
- ComputerManagementDsc.psd1
This PR updates the out-of-date description in the `ComputerManagementDsc.psd1` file.
- Fixes #269 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/270)
> ComputerManagementDsc: Update Description in psd1 File

- CHANGELOG.md
- DSCResources/MSFT_Computer/MSFT_Computer.psm1
- DSCResources/MSFT_OfflineDomainJoin/MSFT_OfflineDomainJoin.psm1
This PR corrects minor style issues highlighted by:
https://github.com/PowerShell/DscResource.Tests/pull/347
@johlju - would you mind reviewing this for me?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/265)
> Fix minor style issues

- CHANGELOG.md
- Examples/Resources/SmbServerConfiguration/1-SmbServerConfiguration_AllProperties_Config.ps1
- Examples/Resources/SmbServerConfiguration/1-SmbServerConfiguration_DisableSmb1_Config.ps1
During the initial review of SMBServerConfiguration, I missed that the CHANGELOG.MD info had slipped out of the UNRELEASED section and that the examples were missing. This PR corrects those issues.
- Fixes #273
@johlju - would you mind reviewing when you have a moment?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/274)
> Added missing examples for SMBServerConfiguration

- CHANGELOG.md
- DSCResources/MSFT_SmbShare/MSFT_SmbShare.psm1
Cleanup duplicate code in Add-SmbShareAccessPermission
- Fixes #226 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/283)
> SmbShare: Add-SmbShareAccessPermission duplicate code removal

- CHANGELOG.md
- DSCResources/MSFT_SmbShare/MSFT_SmbShare.psm1
- DSCResources/MSFT_SmbShare/MSFT_SmbShare.schema.mof
- Tests/Unit/MSFT_SmbShare.Tests.ps1
Adds support to create a share in a specific scope into the SmbShare resource, required for example when creating shares in a Windows cluster.
- Fixes #284 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/291)
> SmbShare: Add support for ScopeName

- CHANGELOG.md
- README.md
This PR fixes the badges for the pipeline as well as adds the missing CHANGELOG.MD entry for the move to the new CI process.
- Fixes #295 
@johlju - can you review for me?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/302)
> Fix Badges

- .gitattributes
- .gitignore
- .vscode/analyzersettings.psd1
- .vscode/settings.json
- .vscode/tasks.json
- CHANGELOG.md
- CONTRIBUTING.md
- RequiredModules.psd1
- build.ps1
- build.yaml
- ComputerManagementDsc
- Added build task `Generate_Conceptual_Help` to generate conceptual help
for the DSC resource.
- Added build task `Generate_Wiki_Content` to generate the wiki content
that can be used to update the GitHub Wiki.
- ComputerManagementDsc
- Updated CI pipeline files.
- No longer run integration tests when running the build task `test`, e.g.
`.\build.ps1 -Task test`. To manually run integration tests, run the
following:
```powershell
.\build.ps1 -Tasks test -PesterScript 'tests/Integration' -CodeCoverageThreshold 0
```
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> ComputerManagementDsc: Update CI pipeline files

- CHANGELOG.md
- RequiredModules.psd1
Pin Pester to 4.10.1 to enable Code Coverage support.
- Fixes #336 
@johlju  - could you review this one when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/337)
> Pin Pester to 4.10.1 - Fixes #336

- CHANGELOG.md
- README.md
- azure-pipelines.yml
Fixes the Code Coverage badge.
@johlju - would you mind reviewing for me? Should be a quick one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/370)
> Correct code coverage badge in README.md

- CHANGELOG.md
- appveyor.yml
- ComputerManagementDsc
- AppVeyor build now sets the correct module version to be able to run tests.
None,
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/416)
> Fix AppVeyor build

- .vscode/analyzersettings.psd1
- .vscode/settings.json
- CHANGELOG.md
- GitVersion.yml
- RequiredModules.psd1
- Resolve-Dependency.ps1
- Resolve-Dependency.psd1
- azure-pipelines.yml
- build.ps1
- build.yaml
- source/Examples/README.md
- tests/Integration/DSC_UserAccountControl.Integration.Tests.ps1
This PR updates the pipeline and supporting files to the latest DSC Community pattern. It also updates the HQRM VM images to run on windows-latest.
- Fixes #427 
Remaining N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/428)
> Update pipeline files to latest version - Fixes #427

- CHANGELOG.md
- appveyor.yml
- source/Classes/020.PSResourceRepository.ps1
- source/DSCResources/DSC_Computer/DSC_Computer.psm1
- source/DSCResources/DSC_OfflineDomainJoin/DSC_OfflineDomainJoin.psm1
- source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1
- source/DSCResources/DSC_SmbShare/DSC_SmbShare.psm1
- source/DSCResources/DSC_SystemLocale/DSC_SystemLocale.psm1
- source/DSCResources/DSC_WindowsCapability/DSC_WindowsCapability.psm1
- source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1
- Made AppVeyor use ModuleFast to resolve dependencies.
None. Pipeline broken in AppVeyor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/441)
> Fix build in AppVeyor

- CHANGELOG.md
- tests/Unit/DSC_UserAccountControl.Tests.ps1
AssertBoundParameters uses an enum on a parameter type. Pester needs to be ignore these.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/445)
> Fix test failure UserAccountControl

- CHANGELOG.md
- source/ComputerManagementDsc.psd1
- source/Examples/Resources/OfflineDomainJoin/1-OfflineDomainJoin_JoinDomainUsingODJBlob_Config.ps1
- source/Examples/Resources/ScheduledTask/7-ScheduledTask_RunPowerShellTaskEvery15Minutes_Config.ps1
- source/Examples/Resources/ScheduledTask/8-ScheduledTask_RunPowerShellTaskEvery15MinutesIndefinitely_Config.ps1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/458)
> Fix module manifest to support class-based resources
