dsccommunity/ComputerManagementDsc

- DSCResources/MSFT_xComputer/MSFT_xComputer.psm1
If only passing in the $Name parameter to Test-TargetResource, the only
required parameter, and $Name –eq $env:COMPUTERNAME, you drop to the
bottom of the function and the function completes without returning a
bool, causing an error.
Since all false cases are covered with existing return, a true return
was added to the end of the function.
> Test-TargetResource returning non-boolean value.

- DSCResources/MSFT_xComputer/MSFT_xComputer.psm1
- Tests/xComputermanagement.Tests.ps1
Looks like this issue had already been fixed in the dev branch!?
However, I didn't find this out until I forked it, switched to the dev branch and updated the test coverage! At least this should stop any future regressions :)
> Fixes #7 and adds test coverage

- DSCResources/MSFT_xComputer/MSFT_xComputer.psm1
- DSCResources/MSFT_xComputer/MSFT_xComputer.schema.mof
- README.md
- Tests/xComputermanagement.Tests.ps1
- appveyor.yml
- xComputerManagement.psd1
> Release of version 1.4.0.0 of xComputerManagement

- DSCResources/MSFT_xComputer/MSFT_xComputer.psm1
- README.md
- Tests/Unit/MSFT_xComputer.Tests.ps1
This addresses issue 29.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/37)
> By specifying the name as localhost the computer can be joined to a domain by its current name

- DSCResources/MSFT_xComputer/MSFT_xComputer.psm1
- README.md
The condition for verifying we're in the correct domain throws a non-terminating error if a child domain was used as input without FQDN. All other functions worked correctly in that scenario except validating the computer is in the correct domain. This change allows lacking FQDN to still return true value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/76)
> DomainName check validates child without FQDN

- .MetaTestOptIn.json
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .vscode/settings.json
- DSCResources/CommonResourceHelper.psm1
- LICENSE
- README.md
- Tests/Unit/MSFT_xComputer.Tests.ps1
- xComputerManagement.psd1
Several of the module files were using UTF8 with BOM encoding. This PR converts them to UTF8 encoding. It also opts into the common tests:
"Common Tests - Validate Module Files"
"Common Tests - Validate Script Files"
The copyright year has also been updated to 2017 in the License.md and the module manifest.
The standard GitHub templates were added and the standard VSCode style settings were included as well.
Fixes #87 
Fixes #88 
Fixes #90
Fixes #91 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/92)
> Fix BOM, Optin to Common Tests, Fix License Year, Add VSCode Styles - Fixes 87

- DSCResources/MSFT_xVirtualMemory/MSFT_xVirtualMemory.psm1
- DSCResources/MSFT_xVirtualMemory/en-US/MSFT_xVirtualMemory.strings.psd1
- README.md
- Tests/Unit/MSFT_xVirtualMemory.Tests.ps1
This PR refactors xVirtualMemory to:
- reduce code duplication
- improve testability (it was very difficult to unit test)
- meet HQRM standards
- increase unit test coverage to 95%
- convert exception calling to use CommonResourceHelper.psm1
- moved strings into localization file
Fixes #95 
Fixes #81
**Task list:**
@Johlju - sorry about the size of this PR, but once I took a look at the existing code and unit tests, I found it wasn't going to be easy to get decent coverage without refactoring. The same with HQRM - the resource needed a lot of work to get it into decent shape.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> xVirtualMemory: Refactor and improve unit test coverage and HQRM - Fixes #95

- DSCResources/MSFT_xComputer/MSFT_xComputer.psm1
- DSCResources/MSFT_xComputer/MSFT_xComputer.schema.mof
- DSCResources/MSFT_xComputer/en-US/MSFT_xComputer.strings.psd1
- README.md
- Tests/Unit/MSFT_xComputer.Tests.ps1
- Tests/Unit/MSFT_xOfflineDomainJoin.tests.ps1
- Tests/Unit/MSFT_xPowerPlan.Tests.ps1
- Tests/Unit/MSFT_xScheduledTask.Tests.ps1
- Tests/Unit/MSFT_xVirtualMemory.Tests.ps1
Convert xComputer resource to HQRM standards and move strings to Localization file.
- Fixes #101 
- Work on #94 
- Work on #80
**Task list:**
@johlju - would you mind reviewing if you get time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/102)
> Convert xComputer to HQRM and move strings to Localization File - Fixes #101

- DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1
- Examples/xScheduledTask/1-CreateScheduledTaskOnce.ps1
- README.md
- Tests/Integration/MSFT_xScheduledTask.Config.ps1
- Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1
- Tests/Unit/MSFT_xScheduledTask.Tests.ps1
This PR enables setting the ExecutionTimeLimit to no limit (indefinite) by setting the parameter to '00:00:00'. Note: setting ExecutionTimeLimit has to be done differently on Windows Server 2012 R2 and Windows Server 2016/Windows 10, so I've added code to handle them all.
#115
**Task list:**
@johlju - if you wouldn't mind and have the time would you be able to review?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/118)
> Fix ExecutionTimeLimit to Enable No Limit - Fixes #115

- DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1
- DSCResources/MSFT_xScheduledTask/en-US/MSFT_xScheduledTask.strings.psd1
- README.md
Convert xScheduledTask to HQRM and move strings to Localization File. Also correct message produced when existing scheduled task trigger type is not recognized.
- Fixes #125
- Fixes #121
**Task list:**
@johlju - this is the last HQRM change required to this module. Would you mind reviewing if you get a chance? I can then get onto the rename and starting work on adding features again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/126)
> xScheduledTask: Move strings to localization file and HQRM - fixes #125

- DSCResources/MSFT_xComputer/MSFT_xComputer.psm1
- README.md
- Tests/Unit/MSFT_xComputer.Tests.ps1
Pull Request to fix issue 44 with xComputer.psm1 where the Get-ComputerDomain function uses a command which LocalSystem doesn't have rights to. Changed to use this instead:
`Get-WmiObject -Class Win32_ComputerSystem`
Fixes #44
**Task list:**
- [x ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/113)
> xComputer: Fixes #44

- README.md
- Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1
- Tests/Integration/MSFT_xVirtualMemory.Integration.Tests.ps1
- Tests/Unit/MSFT_xComputer.Tests.ps1
- Tests/Unit/MSFT_xOfflineDomainJoin.Tests.ps1
- Tests/Unit/MSFT_xPowerPlan.Tests.ps1
- Tests/Unit/MSFT_xScheduledTask.Tests.ps1
- Tests/Unit/MSFT_xVirtualMemory.Tests.ps1
Updated the tests to meet the Pester v4 guidelines.
#106
**Task list:**
@johlju - would you mind looking this one over if you have a chance? I just used the standard script to do the conversion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcomputermanagement/129)
> Updated tests to meet Pester V4 guidelines - Fixes #106

- DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1
- DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.schema.mof
- DSCResources/MSFT_xScheduledTask/en-US/MSFT_xScheduledTask.strings.psd1
- Examples/xScheduledTask/11-DisableABuiltInTask.ps1
- Examples/xScheduledTask/12-DeleteABuiltInTask.ps1
- README.md
- Tests/Integration/MSFT_xScheduledTask.Config.ps1
- Tests/Integration/MSFT_xScheduledTask.Integration.Tests.ps1
- Tests/Unit/MSFT_xScheduledTask.Tests.ps1
* xScheduledTask:
* Add support to disable built-in scheduled tasks - See [Issue #74](https://github.com/PowerShell/xComputerManagement/issues/74).
* Fix unit test mocked schedule task object structure.
* BREAKING CHANGE: xScheduledTask:
* Breaking change because `Get-TargetResource` no longer outputs
`ActionExecutable` and `ScheduleType` properties when the scheduled
task does not exist. It will also include `TaskPath` in output when
scheduled task does not exist.
- Fixes #74
**Task list:**
@johlju - as always would you be able to review for me? I cleaned up the unit tests hashtable layouts because I figured you'd pick up on the incorrect style :grin: - so sorry about the large number of style …
> BREAKING CHANGE: xScheduledTask: Add support for disabling built-in tasks - Fixes #74

- CHANGELOG.md
- Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/MSFT_xScheduledTask.psm1
- Modules/xComputerManagement/DSCResources/MSFT_xScheduledTask/en-US/MSFT_xScheduledTask.strings.psd1
- Tests/Unit/MSFT_xScheduledTask.Tests.ps1
Fixes deletion of scheduled task with unknown or empty task trigger. Get-TargetResource now returns an empty ScheduleType string if the task trigger is empty or unknown instead of throwing an error.
Tasks like Microsoft\Windows\Application Experience\ProgramDataUpdater don't have a valid ScheduleType for the xScheduledTask DSC resource. 
Throwing an error in the Get function is not needed in this case as results of the Get function will be compared with desired state values in the Test function. The empty ScheduledType string will be compared to one the `[ValidateSet('Once', 'Daily', 'Weekly', 'AtStartup', 'AtLogOn')]` mandatory values of  the ScheduledType parameter. The result of the Test function will then be `$false` and the Set function called to …
> xScheduledTask - Fix deletion of scheduled task with unknown or empty task trigger

- CHANGELOG.md
- Modules/ComputerManagementDsc/DSCResources/MSFT_PowerPlan/MSFT_PowerPlan.psm1
- Modules/ComputerManagementDsc/DSCResources/MSFT_PowerPlan/MSFT_PowerPlan.schema.mof
- Tests/Unit/MSFT_PowerPlan.Tests.ps1
Added Read-Only property call IsActive.
Fixes #171 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/193)
> BREAKING CHANGE: PowerPlan: Add IsActive read-only property

- CHANGELOG.md
- Modules/ComputerManagementDsc/DSCResources/MSFT_PowerPlan/MSFT_PowerPlan.psm1
- Modules/ComputerManagementDsc/DSCResources/MSFT_PowerPlan/MSFT_PowerPlan.schema.mof
- Modules/ComputerManagementDsc/DSCResources/MSFT_PowerPlan/en-US/MSFT_PowerPlan.schema.mfl
- Modules/ComputerManagementDsc/DSCResources/MSFT_PowerPlan/en-US/MSFT_PowerPlan.strings.psd1
- Modules/ComputerManagementDsc/Modules/ComputerManagementDsc.Common/ComputerManagementDsc.Common.psm1
- Modules/ComputerManagementDsc/Modules/ComputerManagementDsc.Common/en-us/ComputerManagementDsc.Common.strings.psd1
- Tests/Unit/ComputerManagementDsc.Common.Tests.ps1
- Tests/Unit/MSFT_PowerPlan.Tests.ps1
- appveyor.yml
Changes the PowerPlan resource so that is uses powercfg.exe to get and set power plans instead of the WMI method which is not available or working on all Windows version. This would fix the problems on Windows 10, Windows Server 2019 and Nano Server.
Furthermore the resource accepts now also a GUID as the power plan "name" so the desired plan can be als specified as a GUID when using it on a non-english Windows. 
- Fixes #59 
- Fixes #155 
- Fixes #65 
- [ N/A] Resource documentation added/updated in README.md in the resource folder.
- [N/A ] Examples appropriately added/updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> PowerPlan: Powercfg.exe instead of WMI and allow GUID as power plan name

- .MetaTestOptIn.json
- CHANGELOG.md
- Modules/ComputerManagementDsc/DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
- Modules/ComputerManagementDsc/DSCResources/MSFT_WindowsEventLog/MSFT_WindowsEventLog.psm1
- Modules/ComputerManagementDsc/Examples/Resources/PowerShellExecutionPolicy/1-PowerShellExecutionPolicy_SetPolicy_Config.ps1
- Modules/ComputerManagementDsc/Examples/Resources/PowerShellExecutionPolicy/2-PowerShellExecutionPolicy_SetPolicyForMultipleScopes_Config.ps1
Fix PSSA custom rule violations and opted into Common Tests 'Required Script Analyzer Rules',
'Flagged Script Analyzer Rules', 'New Error-Level Script Analyzer Rules'
'Custom Script Analyzer Rules' and 'Relative Path Length'.
- Fixes #209 
- Fixes #152 
@johlju - would you mind reviewing?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/210)
> Fix PSSA Custom rule violations and opt-in to tests - Fixes #209

- CHANGELOG.md
- DSCResources/MSFT_Computer/MSFT_Computer.psm1
- DSCResources/MSFT_Computer/en-US/MSFT_Computer.strings.psd1
- Tests/Unit/MSFT_Computer.Tests.ps1
This PR fixes the `Directory Service is Busy` error when using the `xComputer` resource to join a domain and rename a computer at the same time, when `JoinOU` is also specified.
This is achieved by catching the `Add-Computer` error, and performing a separate `Rename-Computer` function call if this occurs.
- Fixes #221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/222)
> xComputer: Fix for Error When Joining a Domain and Renaming a Computer when JoinOU is specified

- CHANGELOG.md
- DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
Changes `Get-ScheduledTask` calls to `ScheduledTasks\Get-ScheduledTask` in order to avoid name clash with `Carbon` module
- Fixes #248 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/253)
> [#248] Get-ScheduledTask calls fix to avoid name clashes with Carbon

- CHANGELOG.md
- DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
Fixes `ScheduledTask` `MultipleInstances` type mismatch in `Get-TargeResource`
- Fixes #255 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/256)
> [#255] Fixed type mismatch for MultipleInstances

- DSCResources/MSFT_WindowsCapability/MSFT_WindowsCapability.psm1
- Tests/Unit/MSFT_WindowsCapability.Tests.ps1
The new resource has an issue if you like to disable a Windows Capability.
- Fixes an issue with Set-TargetResource 'Absent'
- Add new Unit Tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/276)
> WindowsCapability: Fix Set-TargetResource

- CHANGELOG.md
- DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
- Tests/Unit/MSFT_ScheduledTask.Tests.ps1
This PR fixes an issue where the ScheduledTask resource will not go into state if the desired description starts or ends with whitespace chars.
- Fixes #258 
@johlju - would you mind reviewing for me when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/computermanagementdsc/279)
> Fix ScheduledTask Description Whitespace issue - Fixes #258

- CHANGELOG.md
- source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1
- tests/Integration/DSC_ScheduledTask.Integration.Tests.ps1
- tests/Integration/DSC_ScheduledTask.config.ps1
- tests/Unit/DSC_ScheduledTask.Tests.ps1
Fixed inconsistent treatment of the BuiltInAccount property for the ScheduledTask resource.
The Set method prefixes the "SYSTEM", "LOCAL SERVICE", "NETWORK SERVICE" account names with the "NT Authority\" domain.
This results in a scheduled task that runs, but the DSC resource test will always fail on the BuiltInAccount property check. For example:
Expected = 'SYSTEM'
Actual = 'NT Authority\SYSTEM.'
Added integration test cases for the ServiceAccount Logontype/BuiltInAccount property, demonstrating the above.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanage …
> ScheduledTask: Resolved inconsistent treatment of BuiltInAccount property.

- CHANGELOG.md
- tests/Integration/DSC_IEEnhancedSecurityConfiguration.Integration.Tests.ps1
- tests/Integration/DSC_PendingReboot.Tests.ps1
- tests/Integration/DSC_PowerShellExecutionPolicy.Integration.Tests.ps1
- tests/Integration/DSC_RemoteDesktopAdmin.Integration.Tests.ps1
- tests/Integration/DSC_ScheduledTask.Integration.Tests.ps1
- tests/Integration/DSC_SmbServerConfiguration.Tests.ps1
- tests/Integration/DSC_SmbShare.Integration.Tests.ps1
- tests/Integration/DSC_SystemLocale.Integration.Tests.ps1
- tests/Integration/DSC_TimeZone.Integration.Tests.ps1
- tests/Integration/DSC_UserAccountControl.Integration.Tests.ps1
- tests/Integration/DSC_VirtualMemory.Integration.Tests.ps1
- tests/Integration/DSC_WindowsCapability.Integration.Tests.ps1
- tests/Integration/DSC_WindowsEventLog.Integration.Tests.ps1
- tests/TestHelpers/CommonTestHelper.psm1
- ComputerManagementDsc
- Improved integration test reliability by resetting the DSC LCM
before executing each test using the `Reset-DscLcm` function - Fixes [Issue #329](https://github.com/dsccommunity/ComputerManagementDsc/issues/329).
- Split integration test MOF compilation out of application to standardize
pattern and make it easier to determine cause of failure.
- Fixes #329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/340)
> Improve integration test reliability - Fixes #329

- CHANGELOG.md
- build.yaml
- source/WikiSource/Home.md
Automate publishing of Wiki content.
- Fixes #342
@johlju - would you mind reviewing his when you get time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/343)
> Automate Wiki Publish - Issue #342

- CHANGELOG.md
- source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1
- tests/Unit/DSC_ScheduledTask.Tests.ps1
This PR fixes the issue where disabling certain scheduled tasks does not work.
- Fixes #306 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/346)
> Fixed issue #306

- CHANGELOG.md
- source/DSCResources/DSC_PendingReboot/DSC_PendingReboot.psm1
- source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1
This PR corrects Pending Reboot to use `Get-LocalizedData` to read data so that it will work on non en-US OS.
- Fixes #350 
@johlju - would you mind reviewing this one for me?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/351)
> Fix PendingReboot Localized Data issue - Fixes #350

- CHANGELOG.md
- source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1
Skip testing for StartTime when no StartTime is specified and ScheduleType is Once, Daily, or Weekly.
- Fixes #148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/357)
> ScheduledTask: Remove comparison of StartTime if StartTime is not provided

- CHANGELOG.md
- README.md
- RequiredModules.psd1
- azure-pipelines.yml
- build.yaml
- codecov.yml
This PR adds Code Coverage support, fixes an issue with Publishing the module (due to the case being wrong on the tasks - I think) and updates Sampler.
- Fixes #367 
- Fixes #365 
- Fixes #368 
@johlju - would you mind reviewing when you get time? I think I have an issue in all modules where publish is failing because the case of the Sampler tasks has changed. But I've yet to confirm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/369)
> Added Code Coverage and fix Publish

- CHANGELOG.md
- README.md
- azure-pipelines.yml
This PR updates the pipeline to correct the last pipeline task and remove unused environment variables.
N/A
@johlju - would you mind reviewing when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/372)
> Remove unused environment variables from pipeline

- CHANGELOG.md
- source/DSCResources/DSC_Computer/DSC_Computer.psm1
- source/DSCResources/DSC_Computer/en-US/DSC_Computer.strings.psd1
- tests/Unit/DSC_Computer.Tests.ps1
When joining a computer to a domain, if a computer object with the same name already exists in the domain it will be deleted.
- Fixes #55 
- Fixes #58 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386)
> Computer: Delete existing AD Computer object when joining Computer to Domain

- CHANGELOG.md
- source/ComputerManagementDsc.psd1
- ComputerManagementDsc
- The resource names was removed from the property `DscResourcesToExport`
in the module manifest in the source folder since the built module is
automatically updated with this information by the pipeline. Fixes [Issue #396](https://github.com/dsccommunity/ComputerManagementDsc/issues/396).
- Fixes #396
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/397)
> ComputerManagementDsc: Remove resource named from module manifest in `source`

- CHANGELOG.md
- source/DSCResources/DSC_Computer/DSC_Computer.psm1
This fixes the function Delete-ADSIObject by changing the variable used when creating System.DirectoryServices.DirectoryEntry.
Fixes #414 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/415)
> DSC_Computer: Fix for Delete-ADSIObject

- CHANGELOG.md
- source/DSCResources/DSC_SmbShare/DSC_SmbShare.psm1
- source/DSCResources/DSC_UserAccountControl/DSC_UserAccountControl.psm1
Allow SmbShare Test-TargetResource to succeed when access entries use different order
Ensure registry keys of UserAccountControl are created as REG_DWORD rather than REG_SZ
- Fixes #247
- Fixes #423
- Fixes #412
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/424)
> SmbShare, UserAccountControl - fix issues with access control parameters, DWord registry value types

- CHANGELOG.md
- source/DSCResources/DSC_Computer/DSC_Computer.psm1
- tests/Unit/DSC_Computer.Tests.ps1
Spotted this issue the other day - when requesting the NETBIOS domain name, Get-ComputerDomain is returning the user's domain name, not the computer's. It is possible for a user from another domain to log on to this computer.
It looks like the NETBIOS functionality is not actually used at present, but fixing this in case it is used in future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/444)
> Fix Get-DomainName - retrieve computer NETBIOS domain name instead of user
